### PR TITLE
Recursor pkg resource

### PR DESCRIPTION
**Pull request by jmauro**
Hello,

The goal of this PR, is to be able to overwrite the repositories URL for recursor (https://github.com/dnsimple/chef-pdns/issues/50).

Do not hesitate, to tell me what you want me to change. Really do not feel embarrass if doesn't fulfill your needs.

Regards,
JM

PS: Once https://github.com/dnsimple/chef-pdns/pull/72 will be merged, this PR will be less longer.

### CODE REVIEW

**Comment by martinisoft** [comment]
Hi @jmauro and thanks for sending in a pull request. After a quick glance, the first thing that strikes me is the drastic changes to our Rakefile. I think that is out of the scope of this pull request and you are welcome to propose a separate pull request for those changes specifically. Once you do, go ahead and ping on the issue here and I'll re-mark it as ready for review for the team so we take a look.

**Comment by martinisoft** [comment]
Speaking of that I just noticed #72 in conjunction with this PR. Are they the same changes or separate?

**Comment by jmauro** [comment]
This is the same PR just for the rake file, I just rebase it based on https://github.com/dnsimple/chef-pdns/pull/72 otherwise the tests are too long.
So quick answer YES... Merge https://github.com/dnsimple/chef-pdns/pull/72 :) and this PR will be shorter...

**Comment by martinisoft** [comment]
Hi jmauro. Since we've merged #72 you can re-factor this PR. Otherwise it cannot be merged as-is due to conflicts.

**Comment by martinisoft** [comment]
Hi @jmauro 

Thanks for submitting this pull request. I've just overhauled and re-written the resources to simplify everything in terms of installation. Please re-base against current master then we can re-review.

**Comment by jmauro** [comment]
Will do ASAP.

Regards,
JM

**Comment by martinisoft** [comment]
@jmauro Looks like you've still got a merge conflict and CI failures.

**Comment by onlyhavecans** [comment]
Hello @jmauro Since we haven't gotten any feedback lately and this will not merge we are going to close it for now. If you are interested in it still it should be rebaseable!

**Pull request closed without merging**
