### PR TITLE
Add DNF / CentOS 8 - drop CentOS 6

### PR DESCRIPTION
**Pull request by sspans**
The yum_package resource doesn't work on centos / rhel 8.
The package resource maps to yum_package on centos 5/6/7 and to dnf_package on centos 8.

### CODE REVIEW

**Comment by onlyhavecans** [comment]
Thanks for the PR! It looks straightforward to me but haved you checked the failing tests?

**Comment by sspans** [comment]
Well they seem to all have failed due to networking issues at travis-ci.
Unfortunately I don't see a button to re-run them.

**Comment by onlyhavecans** [comment]
@sspans Can you rebase this over master again to get updated test?

**Comment by sspans** [comment]
Done!

**Comment by sspans** [comment]
CentOS 8 doesn't have version 4.1 auth/rec available.
I'm not sure on how to best resolve this, I've elected to change the defaults to
the latest supported version as described by the powerdns documentation.

I guess this may trigger a bigger version bump, but it seemed like the best option.
Other options would work too, no strong preference from my side.

**Comment by sspans** [comment]
Sigh, a bit more work needed seemingly. I'll give this a poke tomorrow.

**Comment by onlyhavecans** [comment]
I am ok with the version bumps in PowerDNS, it is worth making the defaults latest at this point. If someone needs to pull older packages I think it is reasonable for them to declare the release in the allotted setting.
However, I do see there are still test failures. Is there something we can do to help?

**Comment by sspans** [comment]
No worries, I'll figure out what's up with the remaining failures this weekend.

**Comment by sspans** [comment]
Newer versions of powerdns (4.3)  and powerdns-recursor (4.3) have added user/group to the systemd service file.
Powerdns will now read the main configuration file already switched to a non-privileged user.

This breaks the run_user / run_group feature in the cookbook, because it assumes user-switching can be done by
configuring the setuid/setgid configuration option.

I see two ways of resolving this:

1. Upstream seems to prefer running with one user account, so drop the run_user feature.
2. Add systemd snippets for virtual instances to set the desired user. 
   - permissions of /etc/pdns will need to be suitable for multiple accounts
   - each user will need a seperate socket-dir, this will require tweaking systemd
   - not sure if this will work properly with pdns_control

I think option 1 would be the most elegant solution.

https://github.com/PowerDNS/pdns/commit/f3d6553235219c02381e6d3477540e9f9fce08ae#diff-8d560dfc64b0336af42c2a808c5b6966
https://github.com/PowerDNS/pdns/commit/7e6d27b7bb5bb1bee492b741d885d5d7a4fe856e#diff-4dbd6f1abdb63a489c30de9bd07b79ff

**Comment by onlyhavecans** [comment]
I generally do not fight against upstream configurations and recommendations in a community cookbook.

Unless @AGS4NO has any concerns I think it might be time to modernize against 4.3 across the board and release a major with a note that if you want this feature for old versions you need to pin back

**Comment by onlyhavecans** [comment]
@sspans Is there anything I can do to help further unblock this or is it an available time issue?

**Comment by sspans** [comment]
Yeah, I'll make time to wrap this week. I see upstream pdns also had some fixes for multiple instances.

**Comment by sspans** [comment]
The sysvinit support handles setuid/setgid differently than the systemd bits.
The only supported sysvinit distro is centos-6, which is EOL on 30/11/2020, 
so it makes sense to  drop sysvinit support and keep things simple.

**Comment by sspans** [comment]
I've bumped the major version to account for the changes included in this PR:

- drop support for centos 6 / sysvinit
- add support for centos 8
- switch to powerdns / recursor 4.3 
- drop run_user / setuid support to match upstream pdns

This seems pretty much done to me, but a full review would be appreciated.
I can run additional checks tomorrow.

**Comment by onlyhavecans** [comment]
Thanks so much! I will pop this only my review queue and also ping @AGS4NO so we can both look into this really soon!

**Comment by sspans** [comment]
Any news on the review? Our internal CI jobs work just fine with this PR.

**Review by onlyhavecans — APPROVED** [review]
This looks great to me as a major release

**Comment by onlyhavecans** [comment]
@sspans Sorry we have been very busy. I have done my review and pinged @AGS4NO as well so we can get this out soon

**Review by AGS4NO — APPROVED** [review]
@sspans Thanks for the PR, this looks great! I will work on getting the new version pushed out to the supermarket this week.

**Comment by mvangoor** [comment]
friendly reminder :)

**Comment by sspans** [comment]
Any update on merging this?

**Comment by mvangoor** [comment]
Hi @AGS4NO @onlyhavecans any chance of a release ? kind of disappointed by the time this is taking...

**Comment by mvangoor** [comment]
Thanks!

**Comment by sspans** [comment]
The new version does not yet seem to be uploaded to the chef supermarket.

https://supermarket.chef.io/cookbooks/pdns

**Pull request merged**
