### PR TITLE
Updates Travis tests to Bionic distribution.

### PR DESCRIPTION
**Pull request by AGS4NO**
Updates Travis tests to Bionic distribution.

Deploy Steps:
-------------
- [ ] Merge to master

Verification Steps:
-------------------
- [ ] Ensure Travis runs finish without failure

### CODE REVIEW

**Comment by AGS4NO** [comment]
[bd2084c](https://github.com/dnsimple/chef-pdns/pull/110/commits/bd2084c43ef78a95341d9957b35134c49e46f32b) gets builds running again in the test matrix. There are still some platform-specific issues (mainly with yum repositories) preventing all tests from passing.

**Comment by AGS4NO** [comment]
Commits up to [a1f2833](https://github.com/dnsimple/chef-pdns/pull/110/commits/a1f283354ed1c62a14c28df7960f34cf0ad15f6d) add support for newer platforms and remove older platforms that are no longer supported.

- The postgresql cookbook does not currently support centos-8
- The default `postgresql.conf` `listen_addresses` is incompatible with Ubuntu in Docker due to IPv6 conflict. 

A possible remedy might be to extract the postgresql setup and use the community cookbook where supported and to use helper resources to setup postgresql on platforms that are not supported by the postgresql cookbook. 

Due to the issues listed above, the following instances have been disabled in the test matrix:
- authoritative-postgres-centos-8
- authoritative-postgres-ubuntu-1604
- authoritative-postgres-ubuntu-1804

**Comment by onlyhavecans** [comment]
Should this be rebased or closed?

**Comment by AGS4NO** [comment]
Closing this as [chef-pdns/pull/114](https://github.com/dnsimple/chef-pdns/pull/114) fixes the CI pipeline and removes unsupported platforms.

Bumping the default series to '43' is non-trivial but required for adding new platform support including CentOS-8 and Ubuntu 20.04 (Ubuntu 20.04 is still waiting on packages to be built in the pdns repo). There are many changes in PowerDNS to permission schemes and default directories that will need to be handled in another PR including warning messages in a minor release that the default series will be changed in the following major release.

**Pull request closed without merging**
